# Generated by Django 6.1.1 on 2026-09-21 17:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        ('suivi', '0010_classe_etat_ecole_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='profil_transition',
        ),
        migrations.CreateModel(
            name='AppartenanceEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('terminee', 'Terminée')], default='active', max_length=10)),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('attribue_le', models.DateTimeField(auto_now_add=True)),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField(blank=True)),
                ('attribue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_attributions', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appartenances', to='suivi.ecole')),
                ('termine_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_retraits', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appartenances_ecoles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ecole', 'utilisateur', '-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='AffectationClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('terminee', 'Terminée')], default='active', max_length=10)),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('attribue_le', models.DateTimeField(auto_now_add=True)),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('responsable', 'Responsable de classe'), ('enseignant_associe', 'Enseignant associé'), ('contributeur', 'Contributeur')], max_length=20)),
                ('attribue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_attributions', to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='suivi.classe')),
                ('termine_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_retraits', to=settings.AUTH_USER_MODEL)),
                ('appartenance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_classes', to='comptes.appartenanceecole')),
            ],
            options={
                'ordering': ['classe', 'appartenance', '-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ResponsabiliteEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('terminee', 'Terminée')], default='active', max_length=10)),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('attribue_le', models.DateTimeField(auto_now_add=True)),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('direction', 'Direction')], default='direction', max_length=20)),
                ('appartenance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsabilites', to='comptes.appartenanceecole')),
                ('attribue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_attributions', to=settings.AUTH_USER_MODEL)),
                ('termine_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_retraits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['appartenance', 'type', '-date_debut'],
            },
        ),
    ]
