# Generated by Django 6.1.1 on 2026-09-22 07:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_remove_utilisateur_ecole_and_more'),
        ('suivi', '0012_demanderapprochementeleve_accesparcourseleve'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalieGouvernance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('classe_sans_responsable', 'Classe sans responsable')], max_length=40)),
                ('motif', models.TextField()),
                ('ouverte_le', models.DateTimeField(auto_now_add=True)),
                ('resolue_le', models.DateTimeField(blank=True, null=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anomalies_gouvernance', to='suivi.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomalies_gouvernance', to='suivi.ecole')),
                ('ouverte_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomalies_gouvernance_ouvertes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ouverte_le'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('selecteur', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('empreinte_jeton', models.CharField(editable=False, max_length=64)),
                ('expire_le', models.DateTimeField()),
                ('etat', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('revoquee', 'Révoquée'), ('expiree', 'Expirée')], default='en_attente', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('acceptee_le', models.DateTimeField(blank=True, null=True)),
                ('revoquee_le', models.DateTimeField(blank=True, null=True)),
                ('acceptee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitations_acceptees', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations_creees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='suivi.ecole')),
                ('revoquee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitations_revoquees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
