# Generated by Django 6.1.1 on 2026-10-04 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_affectationclasse_invitation_preattribuee'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleFacteurCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_chiffree', models.TextField(blank=True)),
                ('confirme_le', models.DateTimeField(blank=True, null=True)),
                ('dernier_pas', models.BigIntegerField(default=0)),
                ('echeance_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='double_facteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
