# Generated by Django 6.1.1 on 2026-10-04 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_double_facteur_compte'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSecoursDoubleFacteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empreinte', models.CharField(max_length=64)),
                ('utilise_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_secours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'empreinte'), name='code_secours_unique_par_compte')],
            },
        ),
    ]
