# Generated by Django 6.1.1 on 2026-09-14 21:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('commune', models.CharField(blank=True, max_length=200)),
                ('mdp_enseignant', models.CharField(editable=False, max_length=256)),
                ('mdp_direction', models.CharField(editable=False, max_length=256)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'école',
                'verbose_name_plural': 'écoles',
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('libelle', models.CharField(max_length=300)),
                ('niveau', models.CharField(choices=[('PS', 'Petite section'), ('MS', 'Moyenne section'), ('GS', 'Grande section')], default='PS', max_length=2)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True, help_text='Décochée, la compétence disparaît de la saisie mais les observations déjà faites sont conservées.')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='suivi.domaine')),
            ],
            options={
                'verbose_name': 'compétence',
                'verbose_name_plural': 'compétences',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='domaine',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaines', to='suivi.ecole'),
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Par exemple : PS-MS de Nadia', max_length=100)),
                ('annee_scolaire', models.CharField(default='2026-2027', max_length=9)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='suivi.ecole')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('niveau', models.CharField(choices=[('PS', 'Petite section'), ('MS', 'Moyenne section'), ('GS', 'Grande section')], default='PS', max_length=2)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='suivi.classe')),
            ],
            options={
                'verbose_name': 'élève',
                'verbose_name_plural': 'élèves',
                'ordering': ['prenom', 'nom'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='domaine',
            unique_together={('ecole', 'code')},
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('reussi', 'Réussi')], default='reussi', max_length=10)),
                ('date_observation', models.DateField(default=django.utils.timezone.localdate)),
                ('commentaire', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='traces/%Y/%m/')),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='suivi.competence')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='suivi.eleve')),
            ],
            options={
                'ordering': ['-date_observation'],
                'unique_together': {('eleve', 'competence')},
            },
        ),
    ]
