# Generated by Django 5.2.15 on 2026-09-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suivi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="statut",
            field=models.CharField(
                choices=[
                    ("non_debute", "Pas commencé"),
                    ("en_cours", "En cours"),
                    ("reussi", "Réussi"),
                ],
                default="reussi",
                max_length=10,
            ),
        ),
    ]
