# Generated by Django 6.1.1 on 2026-09-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0009_supprime_mots_de_passe_partages'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='etat',
            field=models.CharField(choices=[('preparation', 'En préparation'), ('active', 'Active'), ('archivee', 'Archivée')], default='preparation', max_length=11),
        ),
        migrations.AddField(
            model_name='ecole',
            name='etat',
            field=models.CharField(choices=[('preparation', 'En préparation'), ('active', 'Active'), ('desactivee', 'Désactivée')], default='active', max_length=12),
        ),
    ]
