# Generated by Django 6.1.1 on 2026-09-21 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0010_classe_etat_ecole_etat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bilan',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bilans_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bilan',
            name='dernier_editeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bilans_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bilan',
            name='supprime_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bilan',
            name='supprime_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bilans_supprimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trace',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traces_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trace',
            name='dernier_editeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traces_modifiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trace',
            name='supprime_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trace',
            name='supprime_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traces_supprimees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observation',
            name='statut',
            field=models.CharField(blank=True, choices=[('non_debute', 'Pas commencé'), ('en_cours', 'En cours'), ('reussi', 'Réussi')], default='reussi', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='EvenementAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('modele', models.CharField(max_length=80)),
                ('objet_id', models.CharField(max_length=80)),
                ('anciennes_valeurs', models.JSONField(blank=True, default=dict)),
                ('nouvelles_valeurs', models.JSONField(blank=True, default=dict)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements_audit', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit', to='suivi.ecole')),
            ],
            options={
                'ordering': ['-cree_le', '-pk'],
                'indexes': [models.Index(fields=['ecole', 'cree_le'], name='suivi_evene_ecole_i_679095_idx')],
            },
        ),
    ]
