# Generated by Django 6.1.1 on 2026-09-21 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0011_bilan_auteur_bilan_dernier_editeur_bilan_supprime_le_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRapprochementEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_propose', models.CharField(max_length=100)),
                ('nom_propose', models.CharField(blank=True, max_length=100)),
                ('annee_naissance_proposee', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('niveau_propose', models.CharField(choices=[('PS', 'Petite section'), ('MS', 'Moyenne section'), ('GS', 'Grande section')], max_length=2)),
                ('demande_le', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=10)),
                ('decide_le', models.DateTimeField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_rapprochement', to='suivi.classe')),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_rapprochement_decidees', to=settings.AUTH_USER_MODEL)),
                ('demande_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_rapprochement_creees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_rapprochement', to='suivi.ecole')),
                ('eleve_retenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_rapprochement', to='suivi.eleve')),
            ],
            options={
                'ordering': ['demande_le', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AccesParcoursEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valide_le', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acces_parcours_eleves', to='suivi.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acces_parcours', to='suivi.eleve')),
                ('valide_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acces_parcours_valides', to=settings.AUTH_USER_MODEL)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acces_parcours', to='suivi.demanderapprochementeleve')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('eleve', 'classe'), name='acces_parcours_unique_par_eleve_classe')],
            },
        ),
    ]
