# Generated by Django 6.1.1 on 2026-09-29 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0012_demanderapprochementeleve_accesparcourseleve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observation', models.DateField(default=django.utils.timezone.localdate)),
                ('commentaire', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='traces/%Y/%m/')),
                ('supprime_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traces_communes', to='suivi.classe')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traces_communes', to='suivi.competence')),
            ],
            options={
                'ordering': ['date_observation', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='trace',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='suivi.tracecommune'),
        ),
        migrations.AddField(
            model_name='trace',
            name='origine_commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions_personnelles', to='suivi.tracecommune'),
        ),
    ]
