# Generated by Django 6.1.1 on 2026-09-29 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0013_tracecommune_trace_commune_trace_origine_commune'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tracecommune',
            name='dernier_editeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traces_communes_modifiees', to=settings.AUTH_USER_MODEL),
        ),
    ]
