# Generated by Django 6.1.1 on 2026-09-29 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0014_tracecommune_dernier_editeur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='icone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='FormulationLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('heriter', 'Hériter'), ('remplacer', 'Remplacer'), ('desactiver', 'Désactiver')], default='remplacer', max_length=12)),
                ('texte', models.TextField(blank=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.classe')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivi.competence')),
                ('dernier_editeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.ecole')),
                ('origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suivi.formulationproposee')),
                ('origine_locale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adaptations', to='suivi.formulationlocale')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('classe__isnull', True), ('origine__isnull', False)), fields=('ecole', 'origine'), name='formulation_ecole_origine_unique'), models.UniqueConstraint(condition=models.Q(('classe__isnull', False), ('origine__isnull', False)), fields=('classe', 'origine'), name='formulation_classe_origine_unique'), models.UniqueConstraint(condition=models.Q(('origine_locale__isnull', False)), fields=('classe', 'origine_locale'), name='formulation_classe_locale_unique')],
            },
        ),
        migrations.CreateModel(
            name='ReglagePresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('heriter', 'Hériter'), ('remplacer', 'Remplacer'), ('desactiver', 'Désactiver')], default='heriter', max_length=12)),
                ('icone', models.CharField(blank=True, max_length=80)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='presentation/%Y/%m/')),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.classe')),
                ('competence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suivi.competence')),
                ('dernier_editeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.ecole')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('classe__isnull', True), ('competence__isnull', False)), fields=('ecole', 'competence'), name='presentation_ecole_competence_unique'), models.UniqueConstraint(condition=models.Q(('classe__isnull', False), ('competence__isnull', False)), fields=('classe', 'competence'), name='presentation_classe_competence_unique'), models.UniqueConstraint(condition=models.Q(('classe__isnull', True), ('competence__isnull', True)), fields=('ecole',), name='couverture_ecole_unique'), models.UniqueConstraint(condition=models.Q(('classe__isnull', False), ('competence__isnull', True)), fields=('classe',), name='couverture_classe_unique')],
            },
        ),
    ]
