# Generated by Django 6.1.1 on 2026-09-30 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0015_competence_icone_formulationlocale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='suivi.competence'),
        ),
        migrations.CreateModel(
            name='ReferentielAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('etat_initial', models.JSONField(default=dict)),
                ('origine_reprise', models.BooleanField(default=False)),
                ('historique_reconstitue', models.BooleanField(default=False)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referentiels_annuels', to='suivi.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionReferentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courante', models.BooleanField(default=True)),
                ('adopte_le', models.DateTimeField(blank=True, null=True)),
                ('reprise', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoptions_referentiel', to='suivi.classe')),
                ('annuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivi.referentielannuel')),
            ],
        ),
        migrations.CreateModel(
            name='SourceReferentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=120, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('provenance', models.TextField(blank=True)),
                ('licence', models.CharField(blank=True, max_length=120)),
                ('provisoire', models.BooleanField(default=True)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suivi.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='UsageCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_definition', models.CharField(max_length=120)),
                ('adoption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='suivi.adoptionreferentiel')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages_referentiel', to='suivi.competence')),
            ],
        ),
        migrations.CreateModel(
            name='EtatAnnuelObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('statut', models.CharField(blank=True, choices=[('non_debute', 'Pas commencé'), ('en_cours', 'En cours'), ('reussi', 'Réussi')], max_length=10, null=True)),
                ('date_observation', models.DateField(blank=True, null=True)),
                ('connu', models.BooleanField(default=False)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etats_annuels', to='suivi.observation')),
                ('usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suivi.usagecompetence')),
            ],
        ),
        migrations.AddField(
            model_name='trace',
            name='usage_referentiel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suivi.usagecompetence'),
        ),
        migrations.AddField(
            model_name='tracecommune',
            name='usage_referentiel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suivi.usagecompetence'),
        ),
        migrations.CreateModel(
            name='VersionReferentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=80)),
                ('empreinte', models.CharField(max_length=64)),
                ('contenu', models.JSONField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='suivi.sourcereferentiel')),
            ],
        ),
        migrations.AddField(
            model_name='referentielannuel',
            name='version_proposee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivi.versionreferentiel'),
        ),
        migrations.AddField(
            model_name='adoptionreferentiel',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivi.versionreferentiel'),
        ),
        migrations.AddConstraint(
            model_name='usagecompetence',
            constraint=models.UniqueConstraint(fields=('adoption', 'competence'), name='usage_adoption_competence_unique'),
        ),
        migrations.AddConstraint(
            model_name='etatannuelobservation',
            constraint=models.UniqueConstraint(fields=('observation', 'annee_scolaire'), name='etat_observation_annee_unique'),
        ),
        migrations.AddConstraint(
            model_name='versionreferentiel',
            constraint=models.UniqueConstraint(fields=('source', 'numero'), name='version_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='referentielannuel',
            constraint=models.UniqueConstraint(fields=('ecole', 'annee_scolaire'), name='referentiel_ecole_annee_unique'),
        ),
        migrations.AddConstraint(
            model_name='adoptionreferentiel',
            constraint=models.UniqueConstraint(condition=models.Q(('courante', True)), fields=('classe',), name='adoption_courante_classe_unique'),
        ),
    ]
