# Generated by Django 6.1.1 on 2026-09-30 07:11

import django.db.models.deletion
from django.db import migrations, models


def conserver_references_initiales(apps, schema_editor):
    Annuel = apps.get_model("suivi", "ReferentielAnnuel")
    Ressource = apps.get_model("suivi", "RessourceReferentiel")
    alias = schema_editor.connection.alias
    for annuel in Annuel.objects.using(alias).all().iterator():
        for reglage in annuel.etat_initial.get("reglages", []):
            if reglage.get("photo"):
                Ressource.objects.using(alias).get_or_create(annuel_id=annuel.pk, fichier=reglage["photo"])


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0016_fondations_referentiels_annuels'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionreferentiel',
            name='clos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptionreferentiel',
            name='etat_final',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='RessourceReferentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='referentiels/%Y/%m/')),
                ('annuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ressources', to='suivi.referentielannuel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('annuel', 'fichier'), name='ressource_annuelle_fichier_unique')],
            },
        ),
        migrations.RunPython(conserver_references_initiales, migrations.RunPython.noop),
    ]
