# Generated by Django 6.1.1 on 2026-09-30 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0017_cloture_et_ressources_referentiels'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentiteSourceCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=120)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identites', to='suivi.sourcereferentiel')),
            ],
        ),
        migrations.CreateModel(
            name='DefinitionSourceCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='suivi.versionreferentiel')),
                ('identite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='suivi.identitesourcecompetence')),
            ],
        ),
        migrations.AddConstraint(
            model_name='identitesourcecompetence',
            constraint=models.UniqueConstraint(fields=('source', 'identifiant'), name='identite_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='definitionsourcecompetence',
            constraint=models.UniqueConstraint(fields=('version', 'identite'), name='definition_identite_version_unique'),
        ),
    ]
