# Generated by Django 6.1.1 on 2026-09-30 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0018_identites_sources_referentiels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoixApplicationAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9, unique=True)),
                ('configure', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('version_proposee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defauts_application', to='suivi.versionreferentiel')),
                ('versions_autorisees', models.ManyToManyField(blank=True, related_name='choix_application', to='suivi.versionreferentiel')),
            ],
        ),
        migrations.CreateModel(
            name='ChoixEcoleAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('restreindre', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choix_bases_annuels', to='suivi.ecole')),
                ('version_proposee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defauts_ecoles', to='suivi.versionreferentiel')),
                ('versions_autorisees', models.ManyToManyField(blank=True, related_name='choix_ecoles', to='suivi.versionreferentiel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ecole', 'annee_scolaire'), name='choix_bases_ecole_annee_unique')],
            },
        ),
    ]
