# Generated by Django 6.1.1 on 2026-09-30 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0019_choix_bases_annuels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceSourceEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='origine_source', to='suivi.competence')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivi.ecole')),
                ('identite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivi.identitesourcecompetence')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ecole', 'identite'), name='identite_suivi_source_ecole_unique')],
            },
        ),
        migrations.CreateModel(
            name='VersionSourceEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.JSONField()),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivi.ecole')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivi.versionreferentiel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ecole', 'version'), name='version_source_ecole_unique')],
            },
        ),
    ]
