# Generated by Django 6.1.1 on 2026-09-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0020_definitions_sources_ecoles'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionreferentiel',
            name='contenu',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
