# Generated by Django 6.1.1 on 2026-09-30 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0021_contenu_adoptions_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptationCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('libelle', models.CharField(blank=True, max_length=300, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adaptations_referentiel', to='suivi.classe')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adaptations_annuelles', to='suivi.competence')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adaptations_referentiel', to='suivi.ecole')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('classe__isnull', True)), fields=('ecole', 'annee_scolaire', 'competence'), name='adaptation_competence_ecole_annee_unique'), models.UniqueConstraint(condition=models.Q(('classe__isnull', False)), fields=('classe', 'competence'), name='adaptation_competence_classe_unique')],
            },
        ),
    ]
