# Generated by Django 6.1.1 on 2026-09-30 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0022_adaptations_competences_annuelles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('definition', models.JSONField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('classe_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suivi.classe')),
                ('competence', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='origine_locale', to='suivi.competence')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivi.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibiliteCompetenceLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suivi.classe')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disponibilites', to='suivi.competencelocale')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('classe__isnull', True)), fields=('locale', 'annee_scolaire'), name='ajout_propose_ecole_annee_unique'), models.UniqueConstraint(condition=models.Q(('classe__isnull', False)), fields=('locale', 'classe'), name='ajout_repris_classe_unique')],
            },
        ),
    ]
