# Generated by Django 6.1.1 on 2026-09-30 12:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0023_ajouts_locaux_referentiels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondanceCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('reference_depart', models.CharField(max_length=100)),
                ('reference_arrivee', models.CharField(max_length=100)),
                ('origine_depart', models.JSONField()),
                ('origine_arrivee', models.JSONField()),
                ('type_lien', models.CharField(choices=[('lien', 'En lien avec'), ('precise', 'Précise cette compétence'), ('remplace', 'Remplace cette compétence')], max_length=10)),
                ('justification', models.TextField(max_length=1000)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('retire_le', models.DateTimeField(blank=True, null=True)),
                ('arrivee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correspondances_entrantes', to='suivi.competence')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correspondances_validees', to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suivi.classe')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correspondances_sortantes', to='suivi.competence')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivi.ecole')),
                ('retire_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correspondances_retirees', to=settings.AUTH_USER_MODEL)),
                ('version_arrivee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correspondances_entrantes', to='suivi.versionreferentiel')),
                ('version_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correspondances_sortantes', to='suivi.versionreferentiel')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('depart', models.F('arrivee')), _negated=True), name='correspondance_pas_vers_soi'), models.UniqueConstraint(condition=models.Q(('active', True), ('classe__isnull', True)), fields=('ecole', 'annee_scolaire', 'reference_depart', 'reference_arrivee', 'type_lien'), name='correspondance_ecole_active_unique'), models.UniqueConstraint(condition=models.Q(('active', True), ('classe__isnull', False)), fields=('classe', 'reference_depart', 'reference_arrivee', 'type_lien'), name='correspondance_classe_active_unique')],
            },
        ),
    ]
