# Generated by Django 6.1.1 on 2026-10-01 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0024_correspondances_competences'),
    ]

    operations = [
        migrations.AddField(
            model_name='choixapplicationannuel',
            name='changements_apres_saisies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choixapplicationannuel',
            name='historique_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='choixecoleannuel',
            name='changements_apres_saisies',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PermissionChangementClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouverte', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('classe', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='permission_changement', to='suivi.classe')),
            ],
        ),
    ]
