# Generated by Django 6.1.1 on 2026-10-03 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0025_choixapplicationannuel_changements_apres_saisies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolitiqueDoubleFacteurEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatoire_jusqu_au_rang', models.PositiveSmallIntegerField(default=0)),
                ('desactive_a_partir_du_rang', models.PositiveSmallIntegerField(default=6)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('ecole', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='politique_double_facteur', to='suivi.ecole')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('obligatoire_jusqu_au_rang__gte', 0), ('obligatoire_jusqu_au_rang__lte', 5)), name='double_facteur_ecole_obligatoire_entre_0_et_5'), models.CheckConstraint(condition=models.Q(('desactive_a_partir_du_rang__gte', 1), ('desactive_a_partir_du_rang__lte', 6)), name='double_facteur_ecole_desactive_entre_1_et_6'), models.CheckConstraint(condition=models.Q(('obligatoire_jusqu_au_rang__lt', models.F('desactive_a_partir_du_rang'))), name='double_facteur_ecole_obligatoire_avant_desactive')],
            },
        ),
    ]
