# Generated by Django 6.1.2 on 2026-10-08 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0029_export_ecole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('etat', models.CharField(choices=[('attente', 'En attente'), ('preparation', 'En préparation'), ('pret', 'Prêt'), ('echec', 'Échec')], default='attente', max_length=12)),
                ('mot_de_passe_local', models.CharField(blank=True, max_length=256)),
                ('identifiant_local', models.CharField(blank=True, max_length=150)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField()),
                ('instantane_le', models.DateTimeField(blank=True, null=True)),
                ('taille_zip', models.PositiveBigIntegerField(default=0)),
                ('taille_decompressee', models.PositiveBigIntegerField(default=0)),
                ('fichiers', models.PositiveIntegerField(default=0)),
                ('compatible_pwa', models.BooleanField(default=False)),
                ('empreinte', models.CharField(blank=True, max_length=64)),
                ('erreur', models.CharField(blank=True, max_length=200)),
                ('classe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export_local', to='suivi.classe')),
                ('demande_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
