# Generated by Django 6.1.2 on 2026-10-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0030_export_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionreferentiel',
            name='initialisee_depuis_ecole',
            field=models.BooleanField(default=False),
        ),
    ]
